'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StudNok
    Public Property StudentID As String
    Public Property Nok_Name As String
    Public Property Nok_Surname As String
    Public Property Nok_Address As String
    Public Property Nok_Contact As String
    Public Property Nok_Employer As String
    Public Property Nok_EmployerContact As String
    Public Property Nok_EmployerAddress As String
    Public Property Nok_EmployerEmail As String
    Public Property Nok_RelationShip As String
    Public Property Nok_Email As String
    Public Property Nok_refid As Nullable(Of System.Guid)
    Public Property Nok_Employment As String

End Class
